#%RAML 1.0
---
title: "Calculadora"
baseUri: http://localhost:port
version: "v1"
types:
  Calculo: !include includes/calculo.json
/calc:
  /add:
      get:
          description: "Representa la operación de suma y debe ser soportada a través del verbo GET. Va a recibir los elementos a sumar como num1 y num2 como query strings"
          queryParameters:
              num1:
                type: number
                description: "Primer valor de la suma"
                required: true
                example: 1
              num2:
                type: number
                description: "Segundo valor de la suma"
                required: true
                example: 1
          responses:
              200:
                  body:
                      application/json:
                          type: Calculo
  /sub:
      patch:
          description: "Representa la operación de resta y debe ser soportada a través del verbo DELETE. Va a recibir sus elementos a restar como parte del cuerpo del mensaje"
          body:
              application/json:
                  type: Calculo
          responses:
              200:
                body:
                  application/json:
                      type: Calculo
  /mul:
      post:
          description: "Representa la operación de multiplicación y debe ser soportada a través del verbo POST. Va a recibir sus elementos a multiplicar como parte del cuerpo del mensaje"
          body:
              application/json:
                  type: Calculo
          responses:
              200:
                body:
                  application/json:
                      type: Calculo
  /div:
      put:
          description: "RRepresenta la operación de división y debe ser soportada a través del verbo PUT. Va a recibir sus elementos a dividir como num1 y num2 como query strings"
          queryParameters:
              num1:
                  description: "valor del dividendo"
                  type: number
                  required: true
                  example: 1
              num2:
                  description: "valor del divisor"
                  type: number
                  minimum: 1
                  required: true
                  example: 1
          responses:
              200:
                body:
                  application/json:
                      type: Calculo