// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Calculadora.Models
{
    public partial class Calculo
    {
        

        /// <summary>
        /// representa el valor del primer numero
        /// </summary>
        [Required]
		[JsonProperty("num1")]
        public decimal Num1 { get; set; }

        /// <summary>
        /// representa el valor del segundo numero
        /// </summary>
        [Required]
		[JsonProperty("num2")]
        public decimal Num2 { get; set; }

        /// <summary>
        /// representa el resultado de la iperacion realizada entre num1 y mun2
        /// </summary>

		[JsonProperty("result")]
        public decimal? Result { get; set; }
    } // end class

} // end Models namespace

